equinor/fusion-components

- src/components/general/Tabs/Tab.tsx
- src/components/general/Tabs/Tabs.tsx
- src/components/general/Tabs/__stories__/TabContent.tsx
- src/components/general/Tabs/__stories__/Tabs.stories.tsx
- src/components/general/Tabs/__stories__/styles.less
- src/components/general/Tabs/styles.less
- src/hooks/__stories__/KeyboardNavigation.stories.jsx
- src/hooks/useKeyboardNavigation.ts
Added on tab click scroll to tabs component
> Tabs scroll

- src/components/general/IconButton/__stories__/IconButton.stories.tsx
- src/components/icons/components/action/OpenInNewIcon.tsx
- src/components/icons/components/action/index.ts
- src/index.ts
Added a new "Open in new" icon
> added new icon

- src/components/general/Accordion/AccordionItem.tsx
Had to modify the accordion to account for dynamic content, that is content that takes up space after a certain amount of time.
> Modified the accordion to also account for 'dynamic' content

- src/components/general/Accordion/Accordion.stories.tsx
- src/components/general/Accordion/AccordionItem.tsx
Moved to ref to actual div that changes size
> Updated accordion to accomodate dynamic content

- src/components/org/OrgChart/actions.ts
- src/components/org/OrgChart/components/Links.tsx
And set x and y coordinates to null
> Center links in Org Chart 

- package-lock.json
- package.json
- src/components/general/MarkdownViewer/MarkdownViewer.stories.tsx
- src/components/general/MarkdownViewer/index.tsx
- src/components/general/MarkdownViewer/styles.less
- src/index.ts
Simply renders markdown as html
> Added MarkdownViewer component

- src/components/people/PersonCard/index.tsx
Fixed an issue with person card performing excessive and erroneous calls to the backend.
> Bug: PersonCard - Excessive and erroneous calls

- src/components/icons/components/action/index.ts
- src/components/icons/components/wysiwyg/LinkIcon.tsx
- src/components/icons/components/wysiwyg/index.ts
- src/components/org/OrgChart/OrgChart.stories.tsx
- src/components/org/OrgChart/actions.ts
- src/components/org/OrgChart/components/Card.tsx
- src/components/org/OrgChart/components/Labels.tsx
- src/components/org/OrgChart/components/Links.tsx
- src/components/org/OrgChart/components/styles.less
- src/components/org/OrgChart/orgChartTypes.ts
- src/components/org/PositionCard/PositionCard.stories.tsx
- src/components/org/PositionPicker/PositionPicker.stories.tsx
- src/index.ts
- yarn.lock
added linked position  in orgchart
> Linked positions in OrgChart

- src/components/general/Stepper/Step.tsx
- src/components/general/Stepper/StepContent.tsx
- src/components/general/Stepper/StepPane.tsx
- src/components/general/Stepper/Stepper.tsx
- src/components/general/Stepper/__stories__/Stepper.stories.tsx
- src/components/general/Stepper/__stories__/styles.less
- src/components/general/Stepper/index.tsx
- src/components/general/Stepper/styles.less
- src/components/general/Tabs/__stories__/Tabs.stories.tsx
- src/components/icons/components/navigation/ArrowForwardIcon.tsx
- src/components/icons/components/navigation/index.ts
- src/components/org/PositionCard/PositionCard.stories.tsx
- src/components/org/PositionPicker/PositionPicker.stories.tsx
- src/index.ts
Added new component Stepper
Added new component ArrowForwardIcon
> Stepper and ArrowForwardIcon

- src/components/general/Stepper/Stepper.tsx
Fixed an issue that caused stepper to reset position when a child re-renders
> Bug: Stepper resets position

- src/components/general/Stepper/Step.tsx
- src/components/general/Stepper/StepPane.tsx
- src/components/general/Stepper/Stepper.tsx
- src/components/general/Stepper/__stories__/Stepper.stories.tsx
- src/components/general/Stepper/styles.less
Fixed an issue where updating the disabled prop on Step components within the Stepper would not be causing the StepperPane to re-render.
Also made some minor improvements.
> Fixed a bug with Stepper navigation.

- src/components/data/DataTable/components/ExpandedContent.tsx
- src/components/data/DataTable/dataTableTypes.ts
collapsedColumns are now available in custom made ExpandedComponents for the DataTable component
> Added collapsedColumns as a prop to ExpandedComponent

- src/components/general/Accordion/styles.less
- src/components/general/SideSheet/Modal/styles.less
- src/components/org/OrgChart/OrgChart.stories.tsx
- src/components/org/OrgChart/components/Aside.tsx
- src/components/org/OrgChart/components/BreadCrumbs.tsx
- src/components/org/OrgChart/components/Children.tsx
- src/components/org/OrgChart/components/Labels.tsx
- src/components/org/OrgChart/components/LinkedIndicator.tsx
- src/components/org/OrgChart/components/Links.tsx
- src/components/org/OrgChart/index.tsx
- src/components/org/PositionCard/styles.less
- Removed Accordian transition, this was causing issues in edge
- Defined line-height for Position Card to fix Firefox issue
- Org chart spacing
> Edge, Firefox and OrgChart fixes

- src/components/general/SearchableDropdown/index.tsx
- src/components/people/PersonPicker/__stories__/PersonPicker.stories.tsx
- src/components/people/PersonPicker/index.tsx
Also added overrides for placeholder and label to the SearchableDropdown (and PersonPicker)
> SearchableDropdown - Fixed an issue ignoring first input

- src/components/core/Header/index.tsx
- src/components/core/Header/styles.less
Content on the header is now responsive.
> Responsive header on small screens

- src/components/core/Root/index.tsx
- src/components/core/Root/styles.less
- src/components/general/Calendar/index.tsx
- src/components/general/Calendar/styles.less
Header text now have smaller font-size in compact mode
> Changed header sizes in compact mode

- src/components/general/Stepper/StepPane.tsx
- src/components/general/Stepper/Stepper.tsx
- src/components/general/Stepper/__stories__/Stepper.stories.tsx
- src/components/general/Stepper/styles.less
Also improved scrolling when there is not enough horizontal space.
> Added ability to hide nav buttons of Stepper

- src/components/general/Accordion/styles.less
The header and content in the accordion has only a bottom border now.
> Removed borders on accordion

- src/components/general/SideSheet/SideSheet.stories.tsx
Wrong prop in sidesheet story.
> Standard sidesheet fixed prop

- src/components/org/OrgChart/OrgChart.stories.tsx
- src/components/org/PositionCard/PositionCard.stories.tsx
- src/components/org/PositionCard/components/PositionInstance.tsx
- src/components/org/PositionCard/components/PositionTimeline.tsx
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
Fixed dashed line for position card and added percentage to tooltip
> Fixed dashed line for position card

- src/components/general/Slider/Marker.tsx
- src/components/general/Slider/styles.less
Added a prop elevated if you want to have the label on "top" of the slider
> Slider - elevated label

- src/components/general/TextArea/TextArea.stories.tsx
- src/components/general/TextArea/index.tsx
- src/components/general/TextArea/styles.less
Made a new textarea component. The width of the textarea can be controlled outside of the component. 
This textarea component will automatically resize as content changes.
> Textarea component

- src/components/general/SearchableDropdown/SearchableDropdown.stories.tsx
- src/components/general/SearchableDropdown/index.tsx
- src/components/general/SearchableDropdown/styles.less
- src/components/general/TextInput/TextInput.stories.tsx
- src/components/general/TextInput/styles.less
Remove max width from searchable drodown and textinput.
> Remove max width from searchable drodown and textinput.

- src/components/general/SearchableDropdown/SearchableDropdown.stories.tsx
- src/components/general/SearchableDropdown/index.tsx
- src/components/people/PersonPicker/__stories__/PersonPicker.stories.tsx
- src/components/people/PersonPicker/index.tsx
Added error and errormessage on SearchableDropdown. You can now display an error message when you use it. 
Added knob in person picker, to visualize it.
> Searchable dropdown error

- src/components/general/Stepper/Step.tsx
- src/components/general/Stepper/__stories__/Stepper.stories.tsx
- src/components/general/Stepper/styles.less
Changed from two borders on the badge to one
> Stepper - border fix

- src/components/icons/__stories__/Wysiwyg.stories.tsx
- src/components/icons/components/wysiwyg/FormatBoldIcon.tsx
- src/components/icons/components/wysiwyg/FormatItalicsIcon.tsx
- src/components/icons/components/wysiwyg/TitleIcon.tsx
- src/components/icons/components/wysiwyg/index.ts
- src/index.ts
Adding format bold, italic and title icons
Add wysiwyg story
Add Link icon to story
> Adding format bold, italic and title icons

- package-lock.json
- package.json
- src/components/general/SideSheet/Modal/index.tsx
- src/components/general/SideSheet/Modal/styles.less
- src/components/general/SideSheet/SideSheet.stories.tsx
- src/components/general/SideSheet/Standard/index.tsx
- src/components/general/SideSheet/Standard/styles.less
- src/components/general/TextArea/index.tsx
Uses the same sizes for standard sidesheet as modal sidesheet
- xlarge
- large
- medium
- small
Also added onKeyUp on textarea
> Variable sidesheet width

- src/components/icons/__stories__/Navigation.stories.tsx
- src/components/icons/components/navigation/SubdirectoryArrowLeftIcon.tsx
- src/components/icons/components/navigation/SubdirectoryArrowRightIcon.tsx
- src/components/icons/components/navigation/index.ts
- src/index.ts
Add subdirectory right and left arrows
> Add subdirectory right and left arrows

- src/components/general/NavigationDrawer/components/Grouping.tsx
- src/components/general/NavigationDrawer/components/Section.tsx
Removed dropdown arrow when no children and section
> Navigation drawer fix

- package-lock.json
- src/components/general/Slider/index.tsx
The slider does not handle resizing or repositioning the track. To fix this the bounding rect is checked continuously
> Track offset on the slider

- package-lock.json
- package.json
- src/components/core/ContextSelector/__stories__/ContextSelector.stories.tsx
- src/components/core/ContextSelector/index.tsx
Fixed Stories to work with new package.
Fixed bug where selectedValue for dropdown didnt update properly.
It used to set previously selected context instead of the one just selected.
> Context Selector - Simplified context-model

- package.json
- src/index.ts
This is the relvant change
`export { NotificationIcon } from './components/icons/components/alert';`
The rest is formatting/encoding from VS Code...
> Export notification icon

- src/components/general/DatePicker/DatePicker.stories.tsx
- src/components/general/DatePicker/index.tsx
- Take in error and error message to DatePicker  and pass them on to TextInput
- Add example to Storybook
> Add error and error message to DatePicker

- .storybook/withFusionContext.tsx
- package-lock.json
- package.json
- src/components/core/ContextSelector/__stories__/ContextSelector.stories.tsx
- src/components/core/ContextSelector/index.tsx
Nullable, if true in manifest. selector will show a X button. This will remove current context.
placeholder, show custom placeholder in popover when selecting context.
Updated story implemeting the new options.
Updated FusionContext with new ContextBaseUrl. Now using CI
> Context Selector - Implement new options from the App manifest.

- src/components/data/PowerBIReport/index.tsx
- src/components/data/PowerBIReport/models/ReportLevelFilters.ts
- src/index.ts
new Power BI module was not properly exported
> Fixed export off component and models

- src/components/org/PositionCard/PositionCard.stories.tsx
- src/components/org/PositionCard/components/PositionInstance.tsx
- src/components/org/PositionCard/components/PositionTimeline.tsx
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
The cumulative child count was not needed
Also centered childPositionCount button
> Removed cumulative child count

- build/style.js
- package-lock.json
- package.json
- src/components/feedback/Banner/styles.less
- Fix banner content sizing
- Fix css class name hash
> Fix banner content sizing

- src/components/org/PositionPicker/usePositionQuery.tsx
- src/components/people/PersonPhoto/index.tsx
PersonPhoto - Return fallback image if no person id is provided
PositionPicker -Added external id to position picker query
> Minor fixes

- src/components/org/OrgChart/OrgChart.stories.tsx
- src/components/org/OrgChart/actions.ts
- src/components/org/OrgChart/components/Aside.tsx
- src/components/org/OrgChart/components/Card.tsx
- src/components/org/OrgChart/components/Children.tsx
- src/components/org/OrgChart/index.tsx
- src/components/org/OrgChart/orgChartTypes.ts
- src/components/org/OrgChart/store.tsx
- src/components/org/OrgChart/useAdditionalRowHeight.ts
- src/components/org/PositionCard/PositionCard.stories.tsx
- src/components/org/PositionCard/components/RotationInstances.tsx
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
> Support for showing assignee's for rotation positions

- src/components/data/PowerBIReport/index.tsx
Solved problems where filter was reset after it was reapplied by buttonclick handler
> fixing filter issus on with reset filter button

- src/components/org/OrgChart/useAdditionalRowHeight.ts
- src/components/org/PositionCard/components/RotationInstances.tsx
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
- Made sure additional row height is correct
- Added R before showing rotationID
- Moved onClick handler to container
> Org chart - Various fixes

- package-lock.json
- package.json
- src/components/general/AdaptiveCardViewer/AdaptiveCardViewer.stories.tsx
- src/components/general/AdaptiveCardViewer/index.tsx
- src/index.ts
React component wrapper for adaptive cards
> Adaptive card viewer

- src/components/org/OrgChart/components/Root.tsx
- src/components/org/OrgChart/store.tsx
- src/components/org/OrgChart/useAdditionalRowHeight.ts
- src/components/people/PersonCard/styles.less
Org chart - Added support for additional assignee's for root position 
Person card - long names and emails will not overflow
> Org chart show roation fix and person card ellipsis

- src/components/general/SearchableDropdown/index.tsx
- src/components/general/TextInput/index.tsx
- src/components/org/PositionPicker/components/AsideComponent.tsx
- src/components/org/PositionPicker/components/ItemComponent.tsx
- src/components/org/PositionPicker/components/itemComponentProps.ts
- src/components/org/PositionPicker/hooks/usePositionQuery.tsx
- src/components/org/PositionPicker/index.tsx
- Adds optional contractId prop to position picker
- Implements blur on text input to allow closing the searchable dropdown on blur
> Allow selecting contract positions

- src/components/general/Stepper/Step.tsx
> Add description to disabled step

- src/components/general/SideSheet/Modal/index.tsx
- src/components/general/SideSheet/Modal/styles.less
- src/components/general/SideSheet/SideSheet.stories.tsx
Added fullscreen option for Modal sidesheet. uses same width as default maxWidth
> SideSheet - Add Fullscreen modal size options

- src/index.ts
Forgot it had to be exported, since it's a new component
> Add Chip export to src/index.ts

- src/components/general/Chip/__stories__/Chip.stories.tsx
- src/components/general/DatePicker/DatePicker.stories.tsx
- Creating `Chip/__stories__/Chip.stories.tsx`
- Readonly chip
- Removable chip
- `Datepicker.stories.tsx`: 
- Removing unused import
- Fixing variable name typo `setSelecteDate` -> `setSelectedDate`
> Add Chip component to Storybook

- .storybook/config.js
- src/components/general/Chip/__stories__/Chip.stories.tsx
- src/components/general/Chip/index.tsx
- src/components/general/Chip/styles.less
- src/components/general/NavigationDrawer/__stories__/NavigationDrawer.stories.tsx
- src/components/general/NavigationDrawer/components/Child.tsx
- src/components/general/NavigationDrawer/components/Grouping.tsx
- src/components/general/NavigationDrawer/components/Section.tsx
- src/components/general/NavigationDrawer/components/styles.less
- src/components/general/NavigationDrawer/index.tsx
- src/components/general/NavigationDrawer/utils.tsx
And additional Chip color options
> Navigation drawer aside component

- src/components/general/Button/__stories__/Button.stories.tsx
- src/components/general/Button/buttonClasses.ts
- src/components/general/Button/index.tsx
- src/components/general/Button/styles/index.less
- src/components/general/Button/styles/variants.less
- src/styles/colors.less
- Add danger button styling
- Added colors needed for danger button
- Updated hover/active styling for button
The buttons are updated to look more like EDS buttons, but the focus styling is still box shadow.
> Add danger version of button, add colors needed, update button styling

- src/components/general/NavigationDrawer/__stories__/NavigationDrawer.stories.tsx
- src/components/general/NavigationDrawer/components/Grouping.tsx
- src/components/general/NavigationDrawer/components/styles.less
Icons for groupings was not always 48*48
> Navigation drawer - Ensure icon width

- src/components/general/AdaptiveCardViewer/defaultHostConfig.ts
- src/components/general/DatePicker/index.tsx
Also changed default image size for adaptive cards
> fix: Date picker update state on blur and tab press

- package-lock.json
- package.json
- src/components/data/PowerBIReport/index.tsx
only apply `pageChanged` event if embed type is `Report`
> power bi dashboard

- src/components/core/Header/components/NotificationsButton/index.tsx
- src/components/core/Header/index.tsx
- src/components/general/NotificationsSideSheet/NotificationSideSheetContent.tsx
- src/components/general/NotificationsSideSheet/index.tsx
- src/components/general/NotificationsSideSheet/styles.less
- src/components/general/Tabs/Tab.tsx
- src/components/general/Tabs/Tabs.tsx
Added tabs to notification side sheet. 
feat: changed notification side sheet
> Notification side sheet redesign

- src/components/general/NotificationsSideSheet/NotificationDateDivisions.tsx
- src/components/general/NotificationsSideSheet/NotificationSideSheetContent.tsx
- src/components/general/NotificationsSideSheet/styles.less
Added padding on mark all notification as read button
> fix: edited styling on notifications button

- package-lock.json
- package.json
- src/components/data/PowerBIReport/index.tsx
- src/components/general/ErrorMessage/index.tsx
+ standarize error
+ handle each request
+ fix telemetry tracking
+ add error type for 424
+ add error type for 429
> fix: Power BI error messages

- src/components/general/Accordion/AccordionItem.tsx
- src/components/icons/__stories__/AvICon.stories.tsx
- src/components/icons/components/av/PauseCircleIcon.tsx
- src/components/icons/components/av/index.ts
- src/index.ts
Added Pause circle icon
Accordion label can be React component
> feat: Accordion label and new icon

- package-lock.json
- package.json
updated fusion api to get new fix to response parser
> fix: Response Parser from fusion api

- package-lock.json
- package.json
- src/components/data/PowerBIReport/components/ReportEmbed/index.tsx
- src/components/general/BookmarksManager/BookmarkProvider.tsx
- src/components/general/BookmarksManager/BookmarkSideSheet/SideSheetManager/BookmarkForm/index.tsx
- src/components/general/BookmarksManager/BookmarkSideSheet/SideSheetManager/index.tsx
- src/components/general/BookmarksManager/BookmarkSideSheet/index.tsx
- src/components/general/BookmarksManager/index.tsx
A fix for the bookmarks managers in apps where there is no context. The bookmarks will be put under an accordion called "Global" if there is no context.
> check for contextless bookmarks

- src/components/general/RequestWorkflow/CompletedBy.tsx
- src/components/general/RequestWorkflow/WorkflowStep.tsx
- src/components/general/RequestWorkflow/index.tsx
- src/components/general/RequestWorkflow/models.ts
Includes an option to display a person in a specified workflow step with pending state.
E.g display the resource owner of a proposed person in the proposal step if it is still pending
> Feat - Workflow Component - Display a person in a pending workflow step

- package-lock.json
- src/hooks/useHoverToggleController.ts
Fixing error for `setIsPopoverOpen` in usePopoverRef
Before:
Fixed:
> usePopoverRef setState bug

- package-lock.json
- package.json
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
- style type string instead of any
- applying passed background and border before past and future style
- using fusion-react-styles
> fix: card style favors explicitly passed style

- src/components/general/SideSheet/Standard/index.tsx
I want to pass a JSX Element as the title for the sidesheet component.
> chore: change title prop type from string to ReactNode

- src/components/org/PositionTimeline/InlinePositionTimeline/InlineSplit/components/styles.ts
Same color used for PositionTimeline border color
> fix: Changed disabled color for inline position timeline

- src/components/core/ContextSelector/index.tsx
add data-cy to the context selector container and its dropdown
> add data-cy to the context selector container and its dropdown

- src/components/data/PowerBI/Report/components/PowerBIBookmark.tsx
When opening an URL with bookmark parameters, Bookmarks Manager will automatically add that bookmark (filter) to PowerBI. However, we need to wait until the component is loaded before we can apply the filter.
Was a bit unsure if it should check `Loaded` or `rendered`, but after some testing it looks like `Loaded` is sufficient. `rendered` will cause it to wait until all the graphs and stuff are finished rendering.
> fix: dont render bookmarks manager until powerbi is loaded

- package-lock.json
- package.json
- src/components/general/AdaptiveCardViewer/index.tsx
- src/components/general/MarkdownViewer/index.tsx
- src/customElements/components/quick-fact/view/element.ts
becase of security issues marked dep needed to be updated.
+ add intellisense
> fix: update marked syntax

- src/components/general/Tabs/Tabs.tsx
- src/components/general/Tabs/styles.less
> Add sticky tabs

- src/components/general/Tabs/styles.less
Add overflow:auto for tabContent
> Added overflow for tabContent

- src/components/data/DataTable/styles.less
> Revert height changes

- package-lock.json
- package.json
> release: 2.5.22 added base position card

- src/components/data/DataTable/__stories__/DataTable.stories.tsx
- src/components/data/DataTable/components/Table.tsx
- src/components/data/DataTable/dataTableTypes.ts
- src/components/data/DataTable/index.tsx
Added opportunity to create own table styles
> Add options for style

- src/components/general/NavigationDrawer/components/Child.tsx
- src/components/general/NavigationDrawer/components/Grouping.tsx
- src/components/general/NavigationDrawer/components/NavigationItem.tsx
- src/components/general/NavigationDrawer/components/Section.tsx
- src/components/general/NavigationDrawer/index.tsx
- src/components/general/NavigationDrawer/utils.tsx
This feature enables the items in the navigation drawer to be styled as needed.
> feat: styling prop for navigation item in nav drawer

- src/components/data/DataTable/styles.less
Fixes sticky header on DataTable.
Closes #1540.
> fix(DataTable): fixing sticky header for datatable

- package-lock.json
- package.json
Overlap indication on org timeline preview component
> 2.8.0 Overlap indication on org timeline preview component

- src/components/org/PositionPicker/positionToDropdownSection.ts
Fixes bug where for some reason a position name is undefined
> fix: nullcheck on postition picker name

- package-lock.json
- package.json
fix for invalid interval in overlap check
> 2.9.4 Position timeline overlap fix for invalid interval

- src/components/data/PowerBI/Report/components/view/PowerBIReportView.tsx
- src/components/data/PowerBI/Report/components/view/useConfig.ts
PowerBI report reloads on contextchange
> feat(PowerBI): reload report on config change

- package-lock.json
- package.json
- src/components/org/PositionCard/components/PositionIconPhoto.tsx
- src/components/org/PositionCard/index.tsx
- src/components/org/PositionCard/styles.less
Org position cards can now show new property on positions (isProjectManagementTeam).
It will appear as text below exiting icons on left hand side. Warning version will be displayed if property bag does not contain true value for field allowExternalProjectManagementTeam. Which is a setting allowing the allocated person to be part of PMT regardless of external status.
> feat: pmt indication on position card
