equinor/fusion-components

src/components/org/OrgChart/components/Aside.tsx, src/components/org/OrgChart/components/Labels.tsx
Fix for aside when number of aside noes is not an even number and remove labels when no corresponding nodes
=> Org Chart - Labels and Aside fixes

src/hooks/useTooltipRef/index.tsx
Enured useOverlayProtal hook always will be called in useTooltipRef
=> UseTooltipRef hook call order

src/components/general/Button/styles/index.less
When sending an URL prop to the button, the button text has underline like a link (see gif). This PR sets the text decoration to none, to remove the underline
=> Remove text decoration URL-button

src/components/org/PositionCard/styles.less
The expand button with childpositions was overlapping with pims id in compact mode
=> PositionCard - fixed overlapping with pims id in compact mode

src/components/general/Tabs/Tab.tsx
Allows the user to use custom components as tab title
=> React node as a option to tab title

src/components/general/Menu/__stories__/Menu.stories.tsx, src/components/general/Menu/styles.less, src/components/general/SearchableDropdown/SearchableDropdown.stories.tsx
After updating the length on SearchableDropdown (https://github.com/equinor/fusion-components/commit/677c7c8720786d20d8793ccda7090a32caed6981), the selectable items in the dropdown menu does not fill the entire width:
The SearchableDropdown uses the Menu component, and that component has a max widht of `--grid-unit * 70px`. 
This pull request removes the max width of the Menu component. **NOTE**: I don't know where this component is used and what it will affect, so this is a suggestion for a solution to the problem
=> Remove max-width of menu container

src/components/general/SideSheet/Modal/index.tsx, src/components/general/SideSheet/SideSheet.stories.tsx
Added a safeClose prop to the modal side sheet. It will notify the user that the closing was intentional before actually closing it
=> Modale side sheet safe close

package.json, src/components/people/PersonPicker/__stories__/PersonPicker.stories.tsx, src/components/people/PersonPicker/index.tsx
Currently, it is not possible to clear the selected person in the `PersonPicker` component.
To solve this, `selectedPerson` is now passed in as a prop and should be handled by the parent component.
=> SelectedPerson should be handled outside PersonPicker

src/components/general/SideSheet/Modal/styles.less, src/components/general/SideSheet/Standard/index.tsx, src/components/general/SideSheet/Standard/styles.less, src/components/general/SideSheet/useResizablePanel.ts
This also removes transition while resizing for smoother experience and avoids animating the width of open panels on initial render
=> Move SideSheet resize handle to the right when screen placement is left

src/components/general/SideSheet/Standard/styles.less, src/components/general/SideSheet/useResizablePanel.ts
When setting the initial size of a sidesheet, the `isResizing` flag is set to true to allow sidesheets to disable animations for smoother renders, but if the user moves the mouse while setting the initial size the onResize handler will trigger and resize the sidesheet
Split `isResizing` into `isResizing` and `isMouseDown`. When the user is resizing, both `isResizing` and `isMouseDown` is set to **true**, but when programatically resizing (initial render with size from local storage) only `isResizing` is set to true
=> Sidesheet initial resizes on mouse move

src/index.ts
For apps that needs banners, snacks and dialogs from notification center but don't use FusionRoot components.
=> Export notification components

package-lock.json, src/components/data/DataTable/styles.less, src/components/general/FilterPane/index.tsx, src/components/general/FilterPane/styles.less
This PR includes a couple of UI improvements to the `FilterPane` and `DataTable` components.
The Filter Pane UI is not consistent with the `StandardSideSheet` component. If the `screenPlacement` is set to `left`, the collapse button would still render on the left side of the filter pane. The position of the button now respects the screen placement property.
I also created a new css class for the filter pane content so that the header containing the expand/collapse button would not get affected by the content padding. This makes it consistent with the standard side sheet. See example below.
Existing:
New:
If users of the `DataTable` component would like to render a custom component when there is not enough space for the table, a `listComponent` can be provided. The list component however, …
=> UI improvements to FilterPane and DataTable

src/components/core/Container/index.tsx, src/components/core/Container/styles.less, src/components/core/Root/index.tsx
The fusion container uses css grid layout to create seperate areas for the main header and the content. If the container is rendered without a header the area where the header should go is empty, not gone.
Introduce props to the root component to tell fusion to render with or without header
=> Add support for rendering the fusion root and container without the fusion header

src/hooks/useBreakpoint.ts
A bug where useBreakpoint would continuously rerender all components using it as long as the current and new breakpoint are the same
=> Check for breakpoints that are _not_ in the current breakpoints

src/components/data/PowerBIReport/index.tsx, src/components/data/PowerBIReport/models/EventHandlerTypes.ts
When user clicks on the "reset filter" button all filters are removed from the report. 
Including selected context.  Removing context should not be possible. 
A onClickButtonClick event handler has been added to handle this problem.
If reset button is clicked filter will be reapplied to report.
=> Reapply filter when clicking on "reset filter"

src/components/org/PositionCard/PositionCard.stories.tsx, src/components/org/PositionCard/components/PositionInstance.tsx, src/components/org/PositionCard/components/PositionTimeline.tsx, src/components/org/PositionCard/index.tsx, src/components/org/PositionCard/styles.less
When a position has rotation, a pink color is added to the position card timeline to increase visibility.
Added a option to position card to show cumulative child count
=> Position card - Timeline color change for rotation. Cumulative child support

package-lock.json, src/hooks/useHoverToggleController.ts
In the example below (`PersonPhoto`), 3 tooltips/popovers are show at the same time.
This bug was introduced in #230.
The changes in this PR fixes most of the problems, but there is still a problem if you move the pointer over to the smaller circle to see the persons position, and then move it over to the photo to see more details. The move from the small circle to the bigger circle is not detected. Any thoughts on how we can fix this problem would be appreciated. However, I think it is better than the current version.
=> Fixes problem where multiple tooltips was rendered on top of each other

src/components/core/ContextSelector/__stories__/ContextSelector.stories.tsx, src/components/core/Header/index.tsx
Pass header content as a functional component instead of a rendered component.
Temporary workaround to solve [BUG 9880](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/9880).
=> Pass header content as a functional component

src/components/general/FilterPane/countFilters.ts
When FilterPane data is given empty or null values. Counts would end up with negative values. 
Instead of the filters not showing at all, since they should be empty.
This happens because countFiltersAsync jsut returns an empty array when data is empty or a null value. Instead of a object with the filters specified in the sectionDefinitions.
Fix removes the length check for data in the countFiltersAsync. 
countFilters has now an empty array as default value, if its empty. 
This ensures that the filtersCount object with filters specified in the sectionsDefintions gets built properly.
=> Negative counts in filterPane

src/components/people/PersonPicker/index.tsx
If the prop `initialPerson` in PersonPicker is set, it is not possible to clear it out.
This is a fix for it.
=> Added if initialPerson is set to null, then clear section

src/components/data/PowerBIReport/index.tsx
When changing context, selected filter in the report embed (right side filter) are not reset. 
So user might end up with filters that are no longer valid/selectable. 
the new useEffect will reload the report when the context filter get sendt in.
Was not able to find a solution where I was able to reset the filters without reloading.
=> Force reset filters on context change

src/components/data/PowerBIReport/index.tsx
Opening the fly out triggers a rerender and the reload routine starts firing while it doesnt need to.
The end result is the same here.
Removed listening to embedRef from the useEffect that triggers when isLoading changes. As it was causing unnesessery renders.
This useEffect should now only run on reload and initial load.
=> PowerBI Report Component - fixing reload rerender bug

.storybook/config.js, package-lock.json, package.json, src/components/general/MarkdownViewer/index.tsx
It was deprecated and the sanitizer function removed the support for html in markdown
EDIT: Added dompurify to sanitize markdown input
=> Markdown viewer - Update sanitizer

src/components/general/NavigationDrawer/components/styles.less
After adding aside component, the styling for sections did not support long titles
=> Navigation drawer - Fixed styling for section

src/components/data/DataTable/components/Row.tsx, src/components/data/DataTable/utils.ts
Expanded rows was set to auto, taking up as much spaceas it could. 
Changed this to min-content. Making it grow according to expandedContent.
while fixing the white space bug i noticed selection cell bottom-border was not removed when row was expanded. While it was removed on the other columns in that row. 
Added an IsExpanded check on the selection cell when creating rows. 
So the class also get toggled in the same way as the rest.
=>  Expanding table shows too much white space

src/index.ts, src/polyfills/index.ts, src/polyfills/scrollTo.ts
Edge (pre chromium) does not support Element.prototype.scrollTo as used by the stepper and tabs components. Implemented a polyfill which implements a custom version for browsers that does not support scrollTo.
=> Add scrollTo polyfill

src/components/data/DataTable/__stories__/DataTable.stories.tsx, src/components/data/DataTable/__stories__/columns.tsx, src/components/data/DataTable/components/Table.tsx, src/components/data/DataTable/dataTableTypes.ts, src/components/data/DataTable/index.tsx, src/components/data/DataTable/utils.ts
Added a flag to datatable preventing columns to be collapsed
if the table is to wide for the view.
Instead it will just extend outside of the view, with a scrollbar.
size can be controlled by using limiting size off cells in the rows,
or making a custom component for the cell for more granular control.
one caveat here, just setting size on the cell will make it grow to fit. 
That is current behaviour. 
One could make it so the cells do not grow with its content, if its limited.. 
maybe forcing word-wrap/break if the content is to long. 
That would potentially be a breaking change.
=> Data Table no collapsing columns.

src/components/data/DataTable/utils.ts
changed the max off minmax for nonExpanded columns to be min-content  instead of auto. Auto caused the grid to expand columns to fill the height of the space, when you had a smaller amount of columns.
=> Data Table columns expanded to fill full height

src/components/general/FilterPane/__stories__/FilterPane.stories.tsx, src/components/general/FilterPane/index.tsx, src/components/general/FilterPane/styles.less
FilterPane header is now sticked to the top when scrolling.
FilterPane Header can now receive a component.
It will be aligned on the opposite side of the collapse-arrow.
Component will be hidden when collapsing filterpane.
Added a small filter header component to the Filter Pane story. Demoing how this works.
It just flips the filter pane placement back and forth from right to left.
=> Filter Pane - custom component in header 

src/components/general/FilterPane/components/CheckBoxesFilterComponent.tsx
If the label text for checkbox filters get long or breaks into multiple lines. 
The text would squish the width of the check box. 
How much widht the checkbox lost could be different between the filters. 
Cassing them to be unaliged by a couple of pixels and you end up with a fairly messy look. 
To fix this i wrapped checkbox in span tag.
This ensures that the checkbox keeps its size and ratio when the label text gets long or goes over multiple lines
=> Filter Pane - checkboxes get unaligned when text is long

src/components/core/NotificationDialog/index.tsx
Change from p to div to wrap dialog content to open for more semantic markup in the dialog container.
=> Use div instead of p in notification dialog

src/components/data/DataTable/components/ExpandedContent.tsx, src/components/data/DataTable/styles.less, src/components/data/DataTable/utils.ts
Fix to expandedContent by adding a max width.
Should now not expand the size of the table when opened.
Added a no wrap to expanded content label. so that it remains in one line if the row needs to wrap.
In util genrateColumnTemplte was changed for the selection and expanded content cells, making them min-content instead of max-content.
This because they were taking up space when opening up expanded content was opened, even if they were empty or didnt need more space.
causing the actually columns to be pushed further down.
=> Bug 9086: Fusion table component acts funny when long texts are content

src/components/general/Button/__stories__/Button.stories.tsx, src/components/general/Button/styles/index.less
Solution to an open issue. Removed text underline on buttons rendered with <a>.
=> Issue fix - Removed text underline

src/components/data/DataTable/__stories__/DataTable.stories.tsx, src/components/data/DataTable/styles.less
Expandable items had a fit-content property that makes expandable items shorter than the DataTable. Removed that property. Also added a story for table columns with expandable items that is always visible. 
**I don't know if this will impact something important in Fusion!**
**Before**
**After**
=> Make expandable rows 100% width

package-lock.json, package.json, src/components/data/PowerBIReport/__stories__/Reports.stories.tsx, src/components/data/PowerBIReport/components/ReportErrorMessage/index.tsx, src/components/data/PowerBIReport/index.tsx
Added new access check for Context.
Check calls the new checkContextAccess endpoint.
If user does not have access to the choosen context, the ReportErrorMessage will show.
Update ReportErrorMessage to show different header depending on how they got denied access.
If its RLS issue or context issue.
Also added a case for notFound in error handling.
This can happen when the token endpoint did not find the report.
=> feat: Report new context access and error handling

package-lock.json, package.json, src/components/data/PowerBIReport/index.tsx
Access error didnt properly distinguish between Context or Token error.
Meaning you would always get an error saying you dont have access to the context, irregardles if it was report or context at fault.
Also wrapped the checkContextAccess in a callback hook.
=> fix:Report Component : Context Access check bug fixes

src/components/data/HangingGarden/index.tsx, src/index.ts
exporting PIXI from the garden component. Making it unnecessery to in stall pixi in local app. And you get Models becomes available to developers
=> hotfix: Hanging Garden - export PIXI

src/components/general/Tabs/Tabs.tsx
added new prop to Tabs and TabPane, noScrollGradient. 
When there are to many Tabs in a TabPane, the tabs will have a scroll. 
Per standard there is a fadeout gradient on the side where there are tabs outside of view. 
Adding this flag til remove these Gradients, but it does not change the scroll functionality in any way.
=> Tabs - new prop  noScrollGradient.

package-lock.json, package.json, src/components/core/Header/components/FullscreenToggleButton.tsx, src/components/core/Header/index.tsx, src/components/icons/components/action/FullscreenExitIcon.tsx, src/components/icons/components/action/FullscreenIcon.tsx, src/components/icons/components/action/index.ts, src/hooks/useFullscreen.tsx, src/index.ts
New hook useFullscreen : standardized use off fullscreen API. 
Can be used stand alone to set a specific element in an app to be fullscreen. 
Per default the implementation fullscreens the body of the website. Which is the general "F11" behaviour. 
Added new 'Fullscreen Toggle button" to Fusion Header. 
Used to toggle fusion between fullscreen and not. 
Added new icons used by the fullscreen button.
=> Feat: Fullscreen handling

src/components/general/FilterPane/index.tsx
added back the isCollapsed clause for reset button. Else it stay when  pane is collapsed and it looks very out of place
=> fix: filter pane - remove remove filters when pane is collapsed

src/components/data/PowerBIReport/index.tsx
Added error handling for MissingContextRelation.
This happens when the selected context is not setup for use in procosys.
Also revised the NotAuthorized error message. The error now always refers no contex access instead of report.
Been a minor misunderstanding on this one.
=> Powert BI Report - Extended Error Handling

src/components/data/PowerBIReport/components/ReportErrorMessage/index.tsx, src/components/data/PowerBIReport/index.tsx
Fixed issue where changing user would get a white screen when changing context, if user does not have access to report or report does not have RLS Configuration
This happended because the useEffect removed error before checking if the checkContextAccess was even going to run. 
Leaving the user with no error on screen. 
Now the reset for error does not happen before we know checkContextAccess is going to run. 
Also checkContextAccess will not run if there is no accessToken, as there is no need to check this if user does not have access to the report at all. 
This makes sure the no report access takes precedence over no context error. 
Further the ReportErrorMessage component has been extended to facilitate an extra error from the checkContextAccess, "MissingContextRelation"
=> Power BI - Further improvements to Error Handling

src/components/general/BookmarksManager/BookmarkProvider.tsx, src/components/general/BookmarksManager/BookmarkSideSheet/SideSheetManager/Bookmark/index.tsx, src/components/general/BookmarksManager/BookmarkSideSheet/SideSheetManager/index.tsx, src/components/general/BookmarksManager/store/actions/bookmarks.ts, src/components/general/BookmarksManager/store/epics/bookmarks.ts, src/components/general/FilterPane/components/Section.tsx
* When entering a shared bookmark URL (.../apps/....?bookmarkId=xxxx), the payload (e.g. a filter) is automatically applied to the data showed in the app.
* Changed action button label for one modal to a better label. 
* When unsharing a bookmark, a modal will appear asking if you are sure you want to unshare the bookmark. 
* Fix Filter issue where checkboxes and radio buttons wont update when updating filter from bookmark.
=> Bookmarks manager feedback changes

src/components/data/PowerBIReport/components/ReportEmbed/index.tsx
When sharing a bookmark and using the shared URL, the bookmark component has to wait for the Power BI report to be rendered  so the bookmark can be applied to the data set.
=> Render bookmark component after powerbi is rendered

src/components/people/PersonCard/index.tsx, src/components/people/PersonDetail/index.tsx, src/components/people/PersonPhoto/index.tsx, src/components/people/usePeopleDetails.ts
A hook for retrieving a person's details without the odata queries (roles, contracts, positions). The old hook from fusion-api contains all of these three. I could remove them from the fusion-api, however some app may be dependent on them.
=> Remove odata query for Person components

src/components/people/PersonPhoto/AccountTypeBadge.tsx, src/components/people/PersonPhoto/AccountTypeIcon/index.tsx, src/components/people/PersonPhoto/index.tsx
* AccountTypeBadge: Remove the resolver for employee tooltip as well as the ref for the tooltip.
* AccountTypeIcon: Same as AccountTypeBadge
* When hovering the employee icon on a person photo, the employee tooltip will not appear. Instead a popover with more information about the person will appear.
Instead of having two tooltips (tooltip and popover) on two different div-tags, I have now changed the logic to be either or.
The refCheck handles this logic; If there are multiple people or no assigned person it will return the tooltip, and if there is one assigned person it will return the popover.
The tooltip will look like this when hovering a person photo that has not been assigned yet, or if there are additional people:
The popover will look like this when hovering an assigned person:
=> Change PersonPhoto tooltips

src/components/general/FilterPane/components/Filter.tsx, src/components/general/FilterPane/components/Section.tsx
Reverted previous change where  Filter key was set to  changed based on terms updates.
As this caused the Filter to be recreated for each change/selection, making it loose its internal state.
Most notably, this causes the filter to collapse each time a user makes a selection.
This changes was made to fix an issue where filters was not updating when user were applying Bookmarks.
I have made an alternative solution to this inside the Filter component itself.
It will now update based on defaultTerm. So if the filter selection get updated from outside the filter component. It will update its interal term state, reflecting these changes.
=> fix: Filter Pane - Filters collapse on selection/ term update 

src/components/general/FilterPane/components/Filter.tsx
if user applied a bookmark, after selecting filters not part of the bookmark. Those filter was not updated or reset visually
=> fix: FilterPane - reset filters that are not part of bookmark 

src/components/general/ErrorMessage/styles.less
The message prop in ErrorMessage needed a heigh so it will not overlap the "action" button.
=> Adjust height for messages in ErrorMessage component

src/hooks/usePopoverRef/index.tsx
usePopoverRef returns setIsOpen, where you can close the popover outside the component.
When this is done, isPopoverOpen state is not updated. This create a mismatch between the useToggleController open state and internal open state.
And the user needs to double click the ref again next time to get the popover to open.
This fix forces the isPopoverOpen to align with isOpen.
=> usePopoverRef - Open state mismatch 

src/components/general/SideSheet/Standard/index.tsx, src/components/general/SideSheet/Standard/styles.less
It's now possible to pass through another ReactNode prop which will be shown beside the Title text, similar to the Modal sidesheet.
Example usage: 
```typescript
function HeaderContent(): JSX.Element {
return (
<Button frameless url={workOrder?.url} targetBlank>
Button
</Button>
);
}
return(
<SideSheet
title="Title"
isOpen={show}
size={'xlarge'}
onClose={onClose}
id="123"
isResizable={true}
headerContent={<HeaderContent />}
>
);
```
=> feat: Pass through extra content to SideSheet component

src/components/people/PersonDetail/index.tsx
Change the following account names in the PersonDetails component.
Consultant(Red) -> **Contractor/Enterprise**
External(Pink) -> **External/Affiliate**
Definition for external hire should be added 
```
const isExternalHire = !!(
currentPerson.jobTitle && currentPerson.jobTitle.toLowerCase().startsWith('ext')
);
```
External hire should be displayed as **External hire/Consultant**
=> fix: Updated account names

src/components/org/PositionTimeline/components/Split/index.tsx, src/components/org/PositionTimeline/components/Split/styles.ts, src/components/org/PositionTimeline/index.tsx, src/components/org/PositionTimeline/model.ts
Allow for pointer events for disabled timeline splits. This is to show the tool tip even though the split is disabled
=> fix: Position timeline disabled pointer events

src/components/data/PowerBI/Report/PowerBI.tsx, src/components/data/PowerBI/Report/components/PowerBIBookmark.tsx, src/components/data/PowerBI/Report/components/PowerBIReportProvider.tsx, src/components/data/PowerBI/Report/components/view/PowerBIReportView.tsx
Using the new version of Bookmarks Manager component. Related to issue #1330 
Needs to be tested with how the new PowerBI component works (edit: tested it, works fine)
Couple of things:
* AppSettingsManager is deprecated, use BookmarksManager instead
* The `component` ref initialized in the PowerBI provider would always be undefined. It's fixed now by changing the `getEmbeddedComponent` logic. 
* The `contextRef` prop passed to the PowerBI component  would also not be assigned the correct value.
* Using refs in dependency arrays has no effect, so removed them
=> PowerBI -  use new version of bookmarks manager

src/components/org/OrgChart/components/BreadCrumbs.tsx, src/components/org/OrgChart/orgChartTypes.ts
Added optional property **content: JSX.Element** to Breadcrumb. 
Then task owner icon, as described in user story below, can be added for Org Admin and Pro Org charts.
(In One Equinor app we will have opportunity to pass person photo to breadcrumb instead)
DevOps User Story:
[Org chart - Add icon for positions that are Task Owner ](https://statoil-proview.visualstudio.com/Fusion/_backlogs/backlog/Operations%20and%20Improvements/Stories/?showParents=true&workitem=17317)
=> Org Chart Breadcrumb content prop

src/components/general/SideSheet/Standard/styles.less
Remove border-bottom from .collpaseButtonContainer in the sidesheet component.
This added a border under the collapse button when using resizable sidesheet.
But the header container in general does not have an underline. Making this look like a short line sticking out into nothing.
=> fix: Sidesheet - Remove border from collapse button 

src/components/data/PowerBI/Report/store/epics/access-token.ts
Reduced the reset rate for Token Refresh.
At 60 min it refresh after the token has already expired, and it fails.
Now runs after 58 min, in good time before it expires.
Should solve problem with report "disconneting" after 1 hour.
=> Powere BI - Reduced the reset rate for Token Refresh.

src/components/data/DataTable/styles.less
Need to removed the hight for row.
Add the height for clickable tables.
With a lot of data in one cell: 
With one liner data:
=> Added min-height for header section. Remove height for rows

src/components/data/DataTable/styles.less
I remove the row-height in this PR: https://github.com/equinor/fusion-components/pull/1481
But I forgot to remove it for compact mode as well.
=> Remove row-height compact mode

src/components/core/Root/styles.less
[26147](https://statoil-proview.visualstudio.com/Fusion%20Apps%20-%20Product%20Owners/_backlogs/backlog/Equinor%20Resource%20Management/Stories/?workitem=26147
**Copied from Description when changed from User Story to Bug**
The scroll bar on the right hand side is too narrow (invisible). Make the scroll bar wider so that it becomes visible.
Users working without mouse with scroll wheel, cannot find the scroll bar on the side of the windows.
Should be applied to all scroll bars across the apps.
=> !feat: remove scrollbar styling

src/components/people/usePeopleDetails.ts
Updating to use the async `useEffectAsync` from the Fusion package when updating the state with person data, as not doing this can result in errors like
(here observed in the CPR app).
This change should mitigate the warning/error from React, as it no longer will attempt to perform state updates if the component becomes unmounted.
⚠️ This PR was generated by directly modifying the files in GitHub and I do not know if any tests (or other unknown side-effects) will be affected by this change.
=> fix(usePeopleDetails): useEffectAsync

src/components/general/Stepper/Step.tsx
The 'stepPaneRef' was accidentally made non-optional in cd1797b0. This should be optional since the end-user use-case should not normally set this prop.
=> fix: Step props type no longer require 'stepPaneRef'

src/components/general/MarkdownEditor/MarkdownEditor.stories.tsx, src/customElements/components/markdown-editor/element.ts
Added property to ``MarkdownEditor`` component to set minHeight, property aptly named ``minHeight``.
Closes #872
=> feat(MarkdownEditor): Adding property to set editor minHeight

src/components/general/MarkdownEditor/index.tsx
Fixing teardown on MarkdownEditor ref.
Closes #1448
=> fix(MarkDownEditor): teardown only runs if editorRef current is present

src/components/org/PositionTimeline/components/SplitSequence/index.tsx
Overlapping indication on timline preview for position splits can have from date after to date and vice verca.
This invalid interval will cause error. This is a fix for this.
=> Fix: checking for invalid interval for overlapping dates

package-lock.json, package.json, src/components/general/NavigationDrawer/components/Components.style.ts, src/components/general/NavigationDrawer/components/Grouping.tsx, src/components/general/NavigationDrawer/components/NavigationItem.tsx, src/components/general/NavigationDrawer/components/NavigationPopover.tsx, src/components/general/NavigationDrawer/components/Section.tsx
Sections and groupings without a navigation action should not be hoverable in the navigation popover.
If navigation drawer is not collapsed, sections and groupings without a navigation action should show/hide children when clicking anywhere on the item, not just the arrow.
=> NavigationDrawer - Hover and onClick improvements

src/components/people/usePeopleDetails.ts
Issue: _PersonCard_ does not re-render if you first provide an invalid _personId_, then later provide a valid _personId_.
Solution: Reset the error state when executing the try block.
=> fix: PersonCard re-render issue

package-lock.json, package.json, src/components/general/NavigationDrawer/components/Components.style.ts
If a child item in navigationdrawer has a custom background color it overrides the background set on hover. 
Added !important to backgroundColor on hover style to prevent this.
=> Fix: NavigationDrawer Hover on child items with custom background color

src/components/data/DataTable/styles.less
Add overflow for DataTable.
Sticky paginator.
For sticky headers, add:
```
<div style={{overflow: "hidden"}}>
<DataTable/>
</div>
```
=> Fix overflow for datatable

package-lock.json, package.json, src/components/org/PositionCard/components/PositionIconPhoto.tsx, src/components/org/PositionCard/styles.less
Org/position card.
The indication if allocated person was external and external setting was not set, was too scary. So now adjusted to only show PMT in parentheses instead.
=> Fix/ position card pmt external styling
